# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lol_hero.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(960, 560)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(960, 560))
        MainWindow.setMaximumSize(QtCore.QSize(960, 560))
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 960, 35))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(38, 80, 157);")
        self.label.setTextFormat(QtCore.Qt.PlainText)
        self.label.setObjectName("label")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 35, 960, 525))
        self.widget.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-color: rgb(242, 242, 242);")
        self.widget.setObjectName("widget")
        self.tabWidget_1 = QtWidgets.QTabWidget(self.widget)
        self.tabWidget_1.setGeometry(QtCore.QRect(0, 0, 960, 525))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget_1.setFont(font)
        self.tabWidget_1.setAutoFillBackground(False)
        self.tabWidget_1.setStyleSheet("QTabWidget{\n"
"    border:none;\n"
"}\n"
"QTabBar::tab:!selected{\n"
"\n"
"    width: 100px;\n"
"    height:30px;\n"
"    color: rgb(255,255,255);\n"
"    background-color: rgb(63,117,191);\n"
"    border: 1px solid rgb(42,42,42);\n"
"}\n"
"QTabBar::tab:selected{\n"
"    width: 100px;\n"
"    height:30px;\n"
"    color: rgb(64,64,64);\n"
"    background-color: rgb(252,252,252);\n"
"    border: 1px solid rgb(42,42,42);\n"
"}")
        self.tabWidget_1.setObjectName("tabWidget_1")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.line_6 = QtWidgets.QFrame(self.tab_1)
        self.line_6.setGeometry(QtCore.QRect(0, 0, 960, 1))
        self.line_6.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(self.tab_1)
        self.line_7.setGeometry(QtCore.QRect(957, 0, 1, 45))
        self.line_7.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(0, 0, 0);\n"
"border-color: rgb(0, 0, 0);")
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_14 = QtWidgets.QFrame(self.tab_1)
        self.line_14.setGeometry(QtCore.QRect(0, 45, 960, 1))
        self.line_14.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.line_14.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.line_17 = QtWidgets.QFrame(self.tab_1)
        self.line_17.setGeometry(QtCore.QRect(0, 0, 1, 45))
        self.line_17.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(0, 0, 0);\n"
"border-color: rgb(0, 0, 0);")
        self.line_17.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_17.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_17.setObjectName("line_17")
        self.widget_1_1 = QtWidgets.QWidget(self.tab_1)
        self.widget_1_1.setGeometry(QtCore.QRect(0, 0, 960, 45))
        self.widget_1_1.setStyleSheet("QWidget{\n"
"    border:none;\n"
"    background-color: rgb(255,255,255);\n"
"}\n"
"\n"
"    ")
        self.widget_1_1.setObjectName("widget_1_1")
        self.label_1_2 = QtWidgets.QLabel(self.widget_1_1)
        self.label_1_2.setGeometry(QtCore.QRect(320, 6, 81, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_1_2.setFont(font)
        self.label_1_2.setObjectName("label_1_2")
        self.label_1_1 = QtWidgets.QLabel(self.widget_1_1)
        self.label_1_1.setGeometry(QtCore.QRect(660, 6, 101, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_1_1.setFont(font)
        self.label_1_1.setObjectName("label_1_1")
        self.comboBox_1_1 = QtWidgets.QComboBox(self.widget_1_1)
        self.comboBox_1_1.setGeometry(QtCore.QRect(740, 10, 111, 25))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.comboBox_1_1.setFont(font)
        self.comboBox_1_1.setStyleSheet("QComboBox {\n"
"    \n"
"    \n"
"    border-radius:2;\n"
"    border: 1px solid black;\n"
"    padding:0 0 0 15;\n"
"    margin: 0 0 0 5;\n"
"}\n"
"QComboBox::drop-down {\n"
"    \n"
"    border-top-left-radius: 0;     /* 左上角 */\n"
"    border-top-right-radius: 2;    /* 右上角 */\n"
"    border-bottom-left-radius: 0;  /* 左下角 */\n"
"    border-bottom-right-radius: 2; /* 右下角 */\n"
"    border-left-width :  1px ;\n"
"     border-left-color : darkgray;\n"
"     border-left-style :  solid ;  \n"
"    width: 20px;\n"
"    margin: 0;\n"
"}\n"
"QComboBox::down-arrow{\n"
"    image: url(:/background/down_arrow.svg);\n"
"    width: 13px;\n"
"    height:15px;\n"
"}\n"
"\n"
"\n"
"QComboBox QAbstractItemView::item {\n"
"     height :  25px ;\n"
"     padding-left: 10px;\n"
"}\n"
" \n"
"QListView::item {\n"
"     background :  white ;\n"
"}\n"
" \n"
"QListView::item:hover {\n"
"     background :  #BDD7FD ;\n"
"}")
        self.comboBox_1_1.setEditable(True)
        self.comboBox_1_1.setObjectName("comboBox_1_1")
        self.queding_1_1 = QtWidgets.QPushButton(self.widget_1_1)
        self.queding_1_1.setGeometry(QtCore.QRect(895, 10, 50, 25))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.queding_1_1.setFont(font)
        self.queding_1_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.queding_1_1.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(68, 114, 196);\n"
"    border-radius:0;\n"
"    border: 1px solid rgb(64,64,64);\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(255,255,255);\n"
"    background-color: rgb(0, 0, 127);\n"
"    border-radius:0;\n"
"    border: 1px solid rgb(63,117,191);\n"
"}\n"
"QPushButton:pressed{\n"
"border:2px solid white;\n"
"color:white;\n"
"background-color:rgb(0, 0, 127);border-style:outset;\n"
"font: 8pt;}\n"
"")
        self.queding_1_1.setObjectName("queding_1_1")
        self.label_1_3 = QtWidgets.QLabel(self.widget_1_1)
        self.label_1_3.setGeometry(QtCore.QRect(35, 6, 81, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_1_3.setFont(font)
        self.label_1_3.setObjectName("label_1_3")
        self.lineEdit_1_1 = QtWidgets.QLineEdit(self.widget_1_1)
        self.lineEdit_1_1.setGeometry(QtCore.QRect(120, 10, 113, 25))
        self.lineEdit_1_1.setStyleSheet("border-style: outset; \n"
"      border-width: 0.5px; \n"
"      border-color: black;")
        self.lineEdit_1_1.setObjectName("lineEdit_1_1")
        self.lineEdit_1_2 = QtWidgets.QLineEdit(self.widget_1_1)
        self.lineEdit_1_2.setGeometry(QtCore.QRect(400, 10, 181, 25))
        self.lineEdit_1_2.setStyleSheet("border-style: outset; \n"
"      border-width: 0.5px; \n"
"      border-color: black;")
        self.lineEdit_1_2.setObjectName("lineEdit_1_2")
        self.label_1_4 = QtWidgets.QLabel(self.tab_1)
        self.label_1_4.setGeometry(QtCore.QRect(30, 180, 20, 160))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_1_4.setFont(font)
        self.label_1_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_1_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_1_4.setWordWrap(True)
        self.label_1_4.setIndent(-1)
        self.label_1_4.setObjectName("label_1_4")
        self.line_19 = QtWidgets.QFrame(self.tab_1)
        self.line_19.setGeometry(QtCore.QRect(0, 0, 1, 490))
        self.line_19.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(0, 0, 0);\n"
"border-color: rgb(0, 0, 0);")
        self.line_19.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_19.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_19.setObjectName("line_19")
        self.line_18 = QtWidgets.QFrame(self.tab_1)
        self.line_18.setGeometry(QtCore.QRect(957, 0, 1, 490))
        self.line_18.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(0, 0, 0);\n"
"border-color: rgb(0, 0, 0);")
        self.line_18.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_18.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_18.setObjectName("line_18")
        self.line_20 = QtWidgets.QFrame(self.tab_1)
        self.line_20.setGeometry(QtCore.QRect(0, 490, 960, 1))
        self.line_20.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.line_20.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_20.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_20.setObjectName("line_20")
        self.label_1_6 = QtWidgets.QLabel(self.tab_1)
        self.label_1_6.setGeometry(QtCore.QRect(210, 80, 81, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_1_6.setFont(font)
        self.label_1_6.setObjectName("label_1_6")
        self.label_1_8 = QtWidgets.QLabel(self.tab_1)
        self.label_1_8.setGeometry(QtCore.QRect(210, 130, 81, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_1_8.setFont(font)
        self.label_1_8.setObjectName("label_1_8")
        self.lineEdit_1_3 = QtWidgets.QLineEdit(self.tab_1)
        self.lineEdit_1_3.setGeometry(QtCore.QRect(290, 85, 111, 25))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(11)
        self.lineEdit_1_3.setFont(font)
        self.lineEdit_1_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_1_3.setStyleSheet("")
        self.lineEdit_1_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_1_3.setObjectName("lineEdit_1_3")
        self.lineEdit_1_4 = QtWidgets.QLineEdit(self.tab_1)
        self.lineEdit_1_4.setGeometry(QtCore.QRect(290, 135, 111, 25))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(11)
        self.lineEdit_1_4.setFont(font)
        self.lineEdit_1_4.setStyleSheet("")
        self.lineEdit_1_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_1_4.setObjectName("lineEdit_1_4")
        self.lineEdit_1_6 = QtWidgets.QLineEdit(self.tab_1)
        self.lineEdit_1_6.setGeometry(QtCore.QRect(290, 280, 111, 25))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(11)
        self.lineEdit_1_6.setFont(font)
        self.lineEdit_1_6.setStyleSheet("")
        self.lineEdit_1_6.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_1_6.setObjectName("lineEdit_1_6")
        self.label_1_9 = QtWidgets.QLabel(self.tab_1)
        self.label_1_9.setGeometry(QtCore.QRect(210, 275, 71, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_1_9.setFont(font)
        self.label_1_9.setObjectName("label_1_9")
        self.label_1_10 = QtWidgets.QLabel(self.tab_1)
        self.label_1_10.setGeometry(QtCore.QRect(210, 225, 81, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_1_10.setFont(font)
        self.label_1_10.setObjectName("label_1_10")
        self.lineEdit_1_5 = QtWidgets.QLineEdit(self.tab_1)
        self.lineEdit_1_5.setGeometry(QtCore.QRect(290, 230, 111, 25))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(11)
        self.lineEdit_1_5.setFont(font)
        self.lineEdit_1_5.setStyleSheet("")
        self.lineEdit_1_5.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_1_5.setObjectName("lineEdit_1_5")
        self.lineEdit_1_8 = QtWidgets.QLineEdit(self.tab_1)
        self.lineEdit_1_8.setGeometry(QtCore.QRect(290, 425, 111, 25))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(11)
        self.lineEdit_1_8.setFont(font)
        self.lineEdit_1_8.setStyleSheet("")
        self.lineEdit_1_8.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_1_8.setObjectName("lineEdit_1_8")
        self.label_1_11 = QtWidgets.QLabel(self.tab_1)
        self.label_1_11.setGeometry(QtCore.QRect(210, 420, 71, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_1_11.setFont(font)
        self.label_1_11.setObjectName("label_1_11")
        self.label_1_12 = QtWidgets.QLabel(self.tab_1)
        self.label_1_12.setGeometry(QtCore.QRect(210, 370, 81, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_1_12.setFont(font)
        self.label_1_12.setObjectName("label_1_12")
        self.lineEdit_1_7 = QtWidgets.QLineEdit(self.tab_1)
        self.lineEdit_1_7.setGeometry(QtCore.QRect(290, 375, 111, 25))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(11)
        self.lineEdit_1_7.setFont(font)
        self.lineEdit_1_7.setStyleSheet("")
        self.lineEdit_1_7.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_1_7.setObjectName("lineEdit_1_7")
        self.lineEdit_1_13 = QtWidgets.QLineEdit(self.tab_1)
        self.lineEdit_1_13.setGeometry(QtCore.QRect(790, 375, 111, 25))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(11)
        self.lineEdit_1_13.setFont(font)
        self.lineEdit_1_13.setStyleSheet("")
        self.lineEdit_1_13.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_1_13.setObjectName("lineEdit_1_13")
        self.lineEdit_1_10 = QtWidgets.QLineEdit(self.tab_1)
        self.lineEdit_1_10.setGeometry(QtCore.QRect(790, 135, 111, 25))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(11)
        self.lineEdit_1_10.setFont(font)
        self.lineEdit_1_10.setStyleSheet("")
        self.lineEdit_1_10.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_1_10.setObjectName("lineEdit_1_10")
        self.label_1_13 = QtWidgets.QLabel(self.tab_1)
        self.label_1_13.setGeometry(QtCore.QRect(710, 275, 71, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_1_13.setFont(font)
        self.label_1_13.setObjectName("label_1_13")
        self.label_1_14 = QtWidgets.QLabel(self.tab_1)
        self.label_1_14.setGeometry(QtCore.QRect(710, 420, 71, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_1_14.setFont(font)
        self.label_1_14.setObjectName("label_1_14")
        self.lineEdit_1_14 = QtWidgets.QLineEdit(self.tab_1)
        self.lineEdit_1_14.setGeometry(QtCore.QRect(790, 425, 111, 25))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(11)
        self.lineEdit_1_14.setFont(font)
        self.lineEdit_1_14.setStyleSheet("")
        self.lineEdit_1_14.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_1_14.setObjectName("lineEdit_1_14")
        self.label_1_15 = QtWidgets.QLabel(self.tab_1)
        self.label_1_15.setGeometry(QtCore.QRect(710, 225, 81, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_1_15.setFont(font)
        self.label_1_15.setObjectName("label_1_15")
        self.lineEdit_1_11 = QtWidgets.QLineEdit(self.tab_1)
        self.lineEdit_1_11.setGeometry(QtCore.QRect(790, 230, 111, 25))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(11)
        self.lineEdit_1_11.setFont(font)
        self.lineEdit_1_11.setStyleSheet("")
        self.lineEdit_1_11.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_1_11.setObjectName("lineEdit_1_11")
        self.label_1_16 = QtWidgets.QLabel(self.tab_1)
        self.label_1_16.setGeometry(QtCore.QRect(710, 130, 71, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_1_16.setFont(font)
        self.label_1_16.setObjectName("label_1_16")
        self.label_1_5 = QtWidgets.QLabel(self.tab_1)
        self.label_1_5.setGeometry(QtCore.QRect(530, 170, 20, 181))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_1_5.setFont(font)
        self.label_1_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_1_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_1_5.setWordWrap(True)
        self.label_1_5.setIndent(-1)
        self.label_1_5.setObjectName("label_1_5")
        self.lineEdit_1_12 = QtWidgets.QLineEdit(self.tab_1)
        self.lineEdit_1_12.setGeometry(QtCore.QRect(790, 280, 111, 25))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(11)
        self.lineEdit_1_12.setFont(font)
        self.lineEdit_1_12.setStyleSheet("")
        self.lineEdit_1_12.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_1_12.setObjectName("lineEdit_1_12")
        self.label_1_17 = QtWidgets.QLabel(self.tab_1)
        self.label_1_17.setGeometry(QtCore.QRect(710, 370, 71, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_1_17.setFont(font)
        self.label_1_17.setObjectName("label_1_17")
        self.lineEdit_1_9 = QtWidgets.QLineEdit(self.tab_1)
        self.lineEdit_1_9.setGeometry(QtCore.QRect(790, 85, 111, 25))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(11)
        self.lineEdit_1_9.setFont(font)
        self.lineEdit_1_9.setStyleSheet("")
        self.lineEdit_1_9.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_1_9.setObjectName("lineEdit_1_9")
        self.label_1_7 = QtWidgets.QLabel(self.tab_1)
        self.label_1_7.setGeometry(QtCore.QRect(710, 80, 71, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_1_7.setFont(font)
        self.label_1_7.setObjectName("label_1_7")
        self.label_fig_1_1 = QtWidgets.QLabel(self.tab_1)
        self.label_fig_1_1.setGeometry(QtCore.QRect(80, 70, 111, 101))
        self.label_fig_1_1.setText("")
        self.label_fig_1_1.setObjectName("label_fig_1_1")
        self.label_fig_1_2 = QtWidgets.QLabel(self.tab_1)
        self.label_fig_1_2.setGeometry(QtCore.QRect(80, 215, 111, 101))
        self.label_fig_1_2.setText("")
        self.label_fig_1_2.setObjectName("label_fig_1_2")
        self.label_fig_1_3 = QtWidgets.QLabel(self.tab_1)
        self.label_fig_1_3.setGeometry(QtCore.QRect(80, 360, 111, 101))
        self.label_fig_1_3.setText("")
        self.label_fig_1_3.setObjectName("label_fig_1_3")
        self.label_fig_1_4 = QtWidgets.QLabel(self.tab_1)
        self.label_fig_1_4.setGeometry(QtCore.QRect(580, 70, 111, 101))
        self.label_fig_1_4.setText("")
        self.label_fig_1_4.setObjectName("label_fig_1_4")
        self.label_fig_1_5 = QtWidgets.QLabel(self.tab_1)
        self.label_fig_1_5.setGeometry(QtCore.QRect(580, 215, 111, 101))
        self.label_fig_1_5.setText("")
        self.label_fig_1_5.setObjectName("label_fig_1_5")
        self.label_fig_1_6 = QtWidgets.QLabel(self.tab_1)
        self.label_fig_1_6.setGeometry(QtCore.QRect(580, 360, 111, 101))
        self.label_fig_1_6.setText("")
        self.label_fig_1_6.setObjectName("label_fig_1_6")
        self.line_37 = QtWidgets.QFrame(self.tab_1)
        self.line_37.setGeometry(QtCore.QRect(475, 45, 1, 445))
        self.line_37.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(0, 0, 0);\n"
"border-color: rgb(0, 0, 0);")
        self.line_37.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_37.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_37.setObjectName("line_37")
        self.label_3 = QtWidgets.QLabel(self.tab_1)
        self.label_3.setGeometry(QtCore.QRect(770, 470, 181, 20))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(8)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.widget_1_1.raise_()
        self.line_7.raise_()
        self.line_6.raise_()
        self.line_17.raise_()
        self.line_14.raise_()
        self.label_1_4.raise_()
        self.line_19.raise_()
        self.line_18.raise_()
        self.line_20.raise_()
        self.label_1_6.raise_()
        self.label_1_8.raise_()
        self.lineEdit_1_3.raise_()
        self.lineEdit_1_4.raise_()
        self.lineEdit_1_6.raise_()
        self.label_1_9.raise_()
        self.label_1_10.raise_()
        self.lineEdit_1_5.raise_()
        self.lineEdit_1_8.raise_()
        self.label_1_11.raise_()
        self.label_1_12.raise_()
        self.lineEdit_1_7.raise_()
        self.lineEdit_1_13.raise_()
        self.lineEdit_1_10.raise_()
        self.label_1_13.raise_()
        self.label_1_14.raise_()
        self.lineEdit_1_14.raise_()
        self.label_1_15.raise_()
        self.lineEdit_1_11.raise_()
        self.label_1_16.raise_()
        self.label_1_5.raise_()
        self.lineEdit_1_12.raise_()
        self.label_1_17.raise_()
        self.lineEdit_1_9.raise_()
        self.label_1_7.raise_()
        self.label_fig_1_1.raise_()
        self.label_fig_1_2.raise_()
        self.label_fig_1_3.raise_()
        self.label_fig_1_4.raise_()
        self.label_fig_1_5.raise_()
        self.label_fig_1_6.raise_()
        self.line_37.raise_()
        self.label_3.raise_()
        self.tabWidget_1.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.line_1 = QtWidgets.QFrame(self.tab_2)
        self.line_1.setGeometry(QtCore.QRect(0, 0, 1, 510))
        self.line_1.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(0, 0, 0);\n"
"border-color: rgb(0, 0, 0);")
        self.line_1.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_1.setObjectName("line_1")
        self.line_4 = QtWidgets.QFrame(self.tab_2)
        self.line_4.setGeometry(QtCore.QRect(0, 0, 960, 1))
        self.line_4.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(self.tab_2)
        self.line_5.setGeometry(QtCore.QRect(0, 490, 960, 1))
        self.line_5.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_3 = QtWidgets.QFrame(self.tab_2)
        self.line_3.setGeometry(QtCore.QRect(957, 0, 1, 510))
        self.line_3.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(0, 0, 0);\n"
"border-color: rgb(0, 0, 0);")
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_21 = QtWidgets.QFrame(self.tab_2)
        self.line_21.setGeometry(QtCore.QRect(0, 0, 960, 1))
        self.line_21.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.line_21.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_21.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_21.setObjectName("line_21")
        self.line_22 = QtWidgets.QFrame(self.tab_2)
        self.line_22.setGeometry(QtCore.QRect(0, 0, 1, 45))
        self.line_22.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(0, 0, 0);\n"
"border-color: rgb(0, 0, 0);")
        self.line_22.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_22.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_22.setObjectName("line_22")
        self.line_23 = QtWidgets.QFrame(self.tab_2)
        self.line_23.setGeometry(QtCore.QRect(957, 0, 1, 45))
        self.line_23.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(0, 0, 0);\n"
"border-color: rgb(0, 0, 0);")
        self.line_23.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_23.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_23.setObjectName("line_23")
        self.lineEdit_2_4 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_2_4.setGeometry(QtCore.QRect(290, 135, 111, 25))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(11)
        self.lineEdit_2_4.setFont(font)
        self.lineEdit_2_4.setStyleSheet("")
        self.lineEdit_2_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2_4.setObjectName("lineEdit_2_4")
        self.label_1_18 = QtWidgets.QLabel(self.tab_2)
        self.label_1_18.setGeometry(QtCore.QRect(210, 275, 71, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_1_18.setFont(font)
        self.label_1_18.setObjectName("label_1_18")
        self.label_fig_2_5 = QtWidgets.QLabel(self.tab_2)
        self.label_fig_2_5.setGeometry(QtCore.QRect(580, 215, 111, 101))
        self.label_fig_2_5.setText("")
        self.label_fig_2_5.setObjectName("label_fig_2_5")
        self.lineEdit_2_12 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_2_12.setGeometry(QtCore.QRect(790, 280, 111, 25))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(11)
        self.lineEdit_2_12.setFont(font)
        self.lineEdit_2_12.setStyleSheet("")
        self.lineEdit_2_12.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2_12.setObjectName("lineEdit_2_12")
        self.label_1_19 = QtWidgets.QLabel(self.tab_2)
        self.label_1_19.setGeometry(QtCore.QRect(530, 170, 20, 181))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_1_19.setFont(font)
        self.label_1_19.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_1_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_1_19.setWordWrap(True)
        self.label_1_19.setIndent(-1)
        self.label_1_19.setObjectName("label_1_19")
        self.lineEdit_2_13 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_2_13.setGeometry(QtCore.QRect(790, 375, 111, 25))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(11)
        self.lineEdit_2_13.setFont(font)
        self.lineEdit_2_13.setStyleSheet("")
        self.lineEdit_2_13.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2_13.setObjectName("lineEdit_2_13")
        self.label_1_20 = QtWidgets.QLabel(self.tab_2)
        self.label_1_20.setGeometry(QtCore.QRect(710, 370, 71, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_1_20.setFont(font)
        self.label_1_20.setObjectName("label_1_20")
        self.lineEdit_2_8 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_2_8.setGeometry(QtCore.QRect(290, 425, 111, 25))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(11)
        self.lineEdit_2_8.setFont(font)
        self.lineEdit_2_8.setStyleSheet("")
        self.lineEdit_2_8.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2_8.setObjectName("lineEdit_2_8")
        self.lineEdit_2_11 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_2_11.setGeometry(QtCore.QRect(790, 230, 111, 25))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(11)
        self.lineEdit_2_11.setFont(font)
        self.lineEdit_2_11.setStyleSheet("")
        self.lineEdit_2_11.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2_11.setObjectName("lineEdit_2_11")
        self.lineEdit_2_10 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_2_10.setGeometry(QtCore.QRect(790, 135, 111, 25))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(11)
        self.lineEdit_2_10.setFont(font)
        self.lineEdit_2_10.setStyleSheet("")
        self.lineEdit_2_10.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2_10.setObjectName("lineEdit_2_10")
        self.label_1_21 = QtWidgets.QLabel(self.tab_2)
        self.label_1_21.setGeometry(QtCore.QRect(210, 130, 71, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_1_21.setFont(font)
        self.label_1_21.setObjectName("label_1_21")
        self.label_1_22 = QtWidgets.QLabel(self.tab_2)
        self.label_1_22.setGeometry(QtCore.QRect(30, 180, 20, 160))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_1_22.setFont(font)
        self.label_1_22.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_1_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_1_22.setWordWrap(True)
        self.label_1_22.setIndent(-1)
        self.label_1_22.setObjectName("label_1_22")
        self.label_1_23 = QtWidgets.QLabel(self.tab_2)
        self.label_1_23.setGeometry(QtCore.QRect(210, 420, 71, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_1_23.setFont(font)
        self.label_1_23.setObjectName("label_1_23")
        self.lineEdit_2_6 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_2_6.setGeometry(QtCore.QRect(290, 280, 111, 25))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(11)
        self.lineEdit_2_6.setFont(font)
        self.lineEdit_2_6.setStyleSheet("")
        self.lineEdit_2_6.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2_6.setObjectName("lineEdit_2_6")
        self.label_fig_2_3 = QtWidgets.QLabel(self.tab_2)
        self.label_fig_2_3.setGeometry(QtCore.QRect(80, 360, 111, 101))
        self.label_fig_2_3.setText("")
        self.label_fig_2_3.setObjectName("label_fig_2_3")
        self.label_1_24 = QtWidgets.QLabel(self.tab_2)
        self.label_1_24.setGeometry(QtCore.QRect(710, 130, 71, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_1_24.setFont(font)
        self.label_1_24.setObjectName("label_1_24")
        self.label_1_25 = QtWidgets.QLabel(self.tab_2)
        self.label_1_25.setGeometry(QtCore.QRect(210, 370, 81, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_1_25.setFont(font)
        self.label_1_25.setObjectName("label_1_25")
        self.lineEdit_2_5 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_2_5.setGeometry(QtCore.QRect(290, 230, 111, 25))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(11)
        self.lineEdit_2_5.setFont(font)
        self.lineEdit_2_5.setStyleSheet("")
        self.lineEdit_2_5.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2_5.setObjectName("lineEdit_2_5")
        self.label_fig_2_1 = QtWidgets.QLabel(self.tab_2)
        self.label_fig_2_1.setGeometry(QtCore.QRect(80, 70, 111, 101))
        self.label_fig_2_1.setText("")
        self.label_fig_2_1.setObjectName("label_fig_2_1")
        self.label_fig_2_6 = QtWidgets.QLabel(self.tab_2)
        self.label_fig_2_6.setGeometry(QtCore.QRect(580, 360, 111, 101))
        self.label_fig_2_6.setText("")
        self.label_fig_2_6.setObjectName("label_fig_2_6")
        self.lineEdit_2_14 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_2_14.setGeometry(QtCore.QRect(790, 425, 111, 25))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(11)
        self.lineEdit_2_14.setFont(font)
        self.lineEdit_2_14.setStyleSheet("")
        self.lineEdit_2_14.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2_14.setObjectName("lineEdit_2_14")
        self.label_1_26 = QtWidgets.QLabel(self.tab_2)
        self.label_1_26.setGeometry(QtCore.QRect(710, 225, 71, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_1_26.setFont(font)
        self.label_1_26.setObjectName("label_1_26")
        self.lineEdit_2_3 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_2_3.setGeometry(QtCore.QRect(290, 85, 111, 25))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(11)
        self.lineEdit_2_3.setFont(font)
        self.lineEdit_2_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_2_3.setStyleSheet("")
        self.lineEdit_2_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2_3.setObjectName("lineEdit_2_3")
        self.label_1_27 = QtWidgets.QLabel(self.tab_2)
        self.label_1_27.setGeometry(QtCore.QRect(710, 420, 71, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_1_27.setFont(font)
        self.label_1_27.setObjectName("label_1_27")
        self.label_fig_2_2 = QtWidgets.QLabel(self.tab_2)
        self.label_fig_2_2.setGeometry(QtCore.QRect(80, 215, 111, 101))
        self.label_fig_2_2.setText("")
        self.label_fig_2_2.setObjectName("label_fig_2_2")
        self.label_1_28 = QtWidgets.QLabel(self.tab_2)
        self.label_1_28.setGeometry(QtCore.QRect(210, 225, 71, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_1_28.setFont(font)
        self.label_1_28.setObjectName("label_1_28")
        self.label_1_29 = QtWidgets.QLabel(self.tab_2)
        self.label_1_29.setGeometry(QtCore.QRect(710, 275, 71, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_1_29.setFont(font)
        self.label_1_29.setObjectName("label_1_29")
        self.label_1_30 = QtWidgets.QLabel(self.tab_2)
        self.label_1_30.setGeometry(QtCore.QRect(710, 80, 71, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_1_30.setFont(font)
        self.label_1_30.setObjectName("label_1_30")
        self.lineEdit_2_9 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_2_9.setGeometry(QtCore.QRect(790, 85, 111, 25))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(11)
        self.lineEdit_2_9.setFont(font)
        self.lineEdit_2_9.setStyleSheet("")
        self.lineEdit_2_9.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2_9.setObjectName("lineEdit_2_9")
        self.lineEdit_2_7 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_2_7.setGeometry(QtCore.QRect(290, 375, 111, 25))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(11)
        self.lineEdit_2_7.setFont(font)
        self.lineEdit_2_7.setStyleSheet("")
        self.lineEdit_2_7.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2_7.setObjectName("lineEdit_2_7")
        self.label_fig_2_4 = QtWidgets.QLabel(self.tab_2)
        self.label_fig_2_4.setGeometry(QtCore.QRect(580, 70, 111, 101))
        self.label_fig_2_4.setText("")
        self.label_fig_2_4.setObjectName("label_fig_2_4")
        self.label_1_31 = QtWidgets.QLabel(self.tab_2)
        self.label_1_31.setGeometry(QtCore.QRect(210, 80, 71, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_1_31.setFont(font)
        self.label_1_31.setObjectName("label_1_31")
        self.widget_1_2 = QtWidgets.QWidget(self.tab_2)
        self.widget_1_2.setGeometry(QtCore.QRect(0, 0, 960, 45))
        self.widget_1_2.setStyleSheet("QWidget{\n"
"    border:none;\n"
"    background-color: rgb(255,255,255);\n"
"}\n"
"\n"
"    ")
        self.widget_1_2.setObjectName("widget_1_2")
        self.label_1_32 = QtWidgets.QLabel(self.widget_1_2)
        self.label_1_32.setGeometry(QtCore.QRect(320, 6, 81, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_1_32.setFont(font)
        self.label_1_32.setObjectName("label_1_32")
        self.label_1_33 = QtWidgets.QLabel(self.widget_1_2)
        self.label_1_33.setGeometry(QtCore.QRect(660, 6, 101, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_1_33.setFont(font)
        self.label_1_33.setObjectName("label_1_33")
        self.comboBox_2_1 = QtWidgets.QComboBox(self.widget_1_2)
        self.comboBox_2_1.setGeometry(QtCore.QRect(740, 10, 111, 25))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.comboBox_2_1.setFont(font)
        self.comboBox_2_1.setStyleSheet("QComboBox {\n"
"    \n"
"    \n"
"    border-radius:2;\n"
"    border: 1px solid black;\n"
"    padding:0 0 0 15;\n"
"    margin: 0 0 0 5;\n"
"}\n"
"QComboBox::drop-down {\n"
"    \n"
"    border-top-left-radius: 0;     /* 左上角 */\n"
"    border-top-right-radius: 2;    /* 右上角 */\n"
"    border-bottom-left-radius: 0;  /* 左下角 */\n"
"    border-bottom-right-radius: 2; /* 右下角 */\n"
"    border-left-width :  1px ;\n"
"     border-left-color : darkgray;\n"
"     border-left-style :  solid ;  \n"
"    width: 20px;\n"
"    margin: 0;\n"
"}\n"
"QComboBox::down-arrow{\n"
"    image: url(:/background/down_arrow.svg);\n"
"    width: 13px;\n"
"    height:15px;\n"
"}\n"
"\n"
"\n"
"QComboBox QAbstractItemView::item {\n"
"     height :  25px ;\n"
"     padding-left: 10px;\n"
"}\n"
" \n"
"QListView::item {\n"
"     background :  white ;\n"
"}\n"
" \n"
"QListView::item:hover {\n"
"     background :  #BDD7FD ;\n"
"}")
        self.comboBox_2_1.setEditable(True)
        self.comboBox_2_1.setObjectName("comboBox_2_1")
        self.queding_2_1 = QtWidgets.QPushButton(self.widget_1_2)
        self.queding_2_1.setGeometry(QtCore.QRect(895, 10, 50, 25))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.queding_2_1.setFont(font)
        self.queding_2_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.queding_2_1.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(68, 114, 196);\n"
"    border-radius:0;\n"
"    border: 1px solid rgb(64,64,64);\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(255,255,255);\n"
"    background-color: rgb(0, 0, 127);\n"
"    border-radius:0;\n"
"    border: 1px solid rgb(63,117,191);\n"
"}\n"
"QPushButton:pressed{\n"
"border:2px solid white;\n"
"color:white;\n"
"background-color:rgb(0, 0, 127);border-style:outset;\n"
"font: 8pt;}\n"
"")
        self.queding_2_1.setObjectName("queding_2_1")
        self.label_1_34 = QtWidgets.QLabel(self.widget_1_2)
        self.label_1_34.setGeometry(QtCore.QRect(35, 6, 81, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_1_34.setFont(font)
        self.label_1_34.setObjectName("label_1_34")
        self.lineEdit_2_1 = QtWidgets.QLineEdit(self.widget_1_2)
        self.lineEdit_2_1.setGeometry(QtCore.QRect(120, 10, 113, 25))
        self.lineEdit_2_1.setStyleSheet("border-style: outset; \n"
"      border-width: 0.5px; \n"
"      border-color: black;")
        self.lineEdit_2_1.setObjectName("lineEdit_2_1")
        self.lineEdit_2_2 = QtWidgets.QLineEdit(self.widget_1_2)
        self.lineEdit_2_2.setGeometry(QtCore.QRect(400, 10, 181, 25))
        self.lineEdit_2_2.setStyleSheet("border-style: outset; \n"
"      border-width: 0.5px; \n"
"      border-color: black;")
        self.lineEdit_2_2.setObjectName("lineEdit_2_2")
        self.line_13 = QtWidgets.QFrame(self.widget_1_2)
        self.line_13.setGeometry(QtCore.QRect(0, 0, 960, 1))
        self.line_13.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.line_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.line_15 = QtWidgets.QFrame(self.tab_2)
        self.line_15.setGeometry(QtCore.QRect(957, 0, 1, 45))
        self.line_15.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(0, 0, 0);\n"
"border-color: rgb(0, 0, 0);")
        self.line_15.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.line_16 = QtWidgets.QFrame(self.tab_2)
        self.line_16.setGeometry(QtCore.QRect(0, 0, 1, 45))
        self.line_16.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(0, 0, 0);\n"
"border-color: rgb(0, 0, 0);")
        self.line_16.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.line_24 = QtWidgets.QFrame(self.tab_2)
        self.line_24.setGeometry(QtCore.QRect(0, 45, 960, 1))
        self.line_24.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.line_24.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_24.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_24.setObjectName("line_24")
        self.line_36 = QtWidgets.QFrame(self.tab_2)
        self.line_36.setGeometry(QtCore.QRect(475, 45, 1, 445))
        self.line_36.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(0, 0, 0);\n"
"border-color: rgb(0, 0, 0);")
        self.line_36.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_36.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_36.setObjectName("line_36")
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setGeometry(QtCore.QRect(770, 470, 181, 20))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(8)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.tabWidget_1.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.line_8 = QtWidgets.QFrame(self.tab_3)
        self.line_8.setGeometry(QtCore.QRect(0, 0, 1, 490))
        self.line_8.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(0, 0, 0);\n"
"border-color: rgb(0, 0, 0);")
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.line_9 = QtWidgets.QFrame(self.tab_3)
        self.line_9.setGeometry(QtCore.QRect(957, 0, 1, 490))
        self.line_9.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(0, 0, 0);\n"
"border-color: rgb(0, 0, 0);")
        self.line_9.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.line_11 = QtWidgets.QFrame(self.tab_3)
        self.line_11.setGeometry(QtCore.QRect(0, 0, 960, 1))
        self.line_11.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.line_12 = QtWidgets.QFrame(self.tab_3)
        self.line_12.setGeometry(QtCore.QRect(0, 490, 960, 1))
        self.line_12.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.lineEdit_3_9 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_3_9.setGeometry(QtCore.QRect(790, 85, 111, 25))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(11)
        self.lineEdit_3_9.setFont(font)
        self.lineEdit_3_9.setStyleSheet("")
        self.lineEdit_3_9.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_3_9.setObjectName("lineEdit_3_9")
        self.label_1_41 = QtWidgets.QLabel(self.tab_3)
        self.label_1_41.setGeometry(QtCore.QRect(30, 180, 20, 160))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_1_41.setFont(font)
        self.label_1_41.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_1_41.setAlignment(QtCore.Qt.AlignCenter)
        self.label_1_41.setWordWrap(True)
        self.label_1_41.setIndent(-1)
        self.label_1_41.setObjectName("label_1_41")
        self.line_26 = QtWidgets.QFrame(self.tab_3)
        self.line_26.setGeometry(QtCore.QRect(0, 490, 960, 1))
        self.line_26.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.line_26.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_26.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_26.setObjectName("line_26")
        self.label_fig_3_1 = QtWidgets.QLabel(self.tab_3)
        self.label_fig_3_1.setGeometry(QtCore.QRect(80, 70, 111, 101))
        self.label_fig_3_1.setText("")
        self.label_fig_3_1.setObjectName("label_fig_3_1")
        self.lineEdit_3_13 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_3_13.setGeometry(QtCore.QRect(790, 375, 111, 25))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(11)
        self.lineEdit_3_13.setFont(font)
        self.lineEdit_3_13.setStyleSheet("")
        self.lineEdit_3_13.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_3_13.setObjectName("lineEdit_3_13")
        self.label_1_42 = QtWidgets.QLabel(self.tab_3)
        self.label_1_42.setGeometry(QtCore.QRect(210, 275, 71, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_1_42.setFont(font)
        self.label_1_42.setObjectName("label_1_42")
        self.lineEdit_3_12 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_3_12.setGeometry(QtCore.QRect(790, 280, 111, 25))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(11)
        self.lineEdit_3_12.setFont(font)
        self.lineEdit_3_12.setStyleSheet("")
        self.lineEdit_3_12.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_3_12.setObjectName("lineEdit_3_12")
        self.label_1_43 = QtWidgets.QLabel(self.tab_3)
        self.label_1_43.setGeometry(QtCore.QRect(710, 370, 71, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_1_43.setFont(font)
        self.label_1_43.setObjectName("label_1_43")
        self.lineEdit_3_7 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_3_7.setGeometry(QtCore.QRect(290, 375, 111, 25))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(11)
        self.lineEdit_3_7.setFont(font)
        self.lineEdit_3_7.setStyleSheet("")
        self.lineEdit_3_7.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_3_7.setObjectName("lineEdit_3_7")
        self.label_1_44 = QtWidgets.QLabel(self.tab_3)
        self.label_1_44.setGeometry(QtCore.QRect(210, 80, 71, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_1_44.setFont(font)
        self.label_1_44.setObjectName("label_1_44")
        self.line_27 = QtWidgets.QFrame(self.tab_3)
        self.line_27.setGeometry(QtCore.QRect(0, 0, 1, 490))
        self.line_27.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(0, 0, 0);\n"
"border-color: rgb(0, 0, 0);")
        self.line_27.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_27.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_27.setObjectName("line_27")
        self.line_38 = QtWidgets.QFrame(self.tab_3)
        self.line_38.setGeometry(QtCore.QRect(475, 45, 1, 445))
        self.line_38.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(0, 0, 0);\n"
"border-color: rgb(0, 0, 0);")
        self.line_38.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_38.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_38.setObjectName("line_38")
        self.label_fig_3_5 = QtWidgets.QLabel(self.tab_3)
        self.label_fig_3_5.setGeometry(QtCore.QRect(580, 215, 111, 101))
        self.label_fig_3_5.setText("")
        self.label_fig_3_5.setObjectName("label_fig_3_5")
        self.lineEdit_3_10 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_3_10.setGeometry(QtCore.QRect(790, 135, 111, 25))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(11)
        self.lineEdit_3_10.setFont(font)
        self.lineEdit_3_10.setStyleSheet("")
        self.lineEdit_3_10.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_3_10.setObjectName("lineEdit_3_10")
        self.label_fig_3_2 = QtWidgets.QLabel(self.tab_3)
        self.label_fig_3_2.setGeometry(QtCore.QRect(80, 215, 111, 101))
        self.label_fig_3_2.setText("")
        self.label_fig_3_2.setObjectName("label_fig_3_2")
        self.line_10 = QtWidgets.QFrame(self.tab_3)
        self.line_10.setGeometry(QtCore.QRect(957, 0, 1, 45))
        self.line_10.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(0, 0, 0);\n"
"border-color: rgb(0, 0, 0);")
        self.line_10.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.line_28 = QtWidgets.QFrame(self.tab_3)
        self.line_28.setGeometry(QtCore.QRect(0, 45, 960, 1))
        self.line_28.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.line_28.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_28.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_28.setObjectName("line_28")
        self.lineEdit_3_3 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_3_3.setGeometry(QtCore.QRect(290, 85, 111, 25))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(11)
        self.lineEdit_3_3.setFont(font)
        self.lineEdit_3_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_3_3.setStyleSheet("")
        self.lineEdit_3_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_3_3.setObjectName("lineEdit_3_3")
        self.label_fig_3_6 = QtWidgets.QLabel(self.tab_3)
        self.label_fig_3_6.setGeometry(QtCore.QRect(580, 360, 111, 101))
        self.label_fig_3_6.setText("")
        self.label_fig_3_6.setObjectName("label_fig_3_6")
        self.lineEdit_3_8 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_3_8.setGeometry(QtCore.QRect(290, 425, 111, 25))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(11)
        self.lineEdit_3_8.setFont(font)
        self.lineEdit_3_8.setStyleSheet("")
        self.lineEdit_3_8.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_3_8.setObjectName("lineEdit_3_8")
        self.label_1_45 = QtWidgets.QLabel(self.tab_3)
        self.label_1_45.setGeometry(QtCore.QRect(710, 80, 71, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_1_45.setFont(font)
        self.label_1_45.setObjectName("label_1_45")
        self.label_1_46 = QtWidgets.QLabel(self.tab_3)
        self.label_1_46.setGeometry(QtCore.QRect(710, 130, 71, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_1_46.setFont(font)
        self.label_1_46.setObjectName("label_1_46")
        self.lineEdit_3_14 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_3_14.setGeometry(QtCore.QRect(790, 425, 111, 25))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(11)
        self.lineEdit_3_14.setFont(font)
        self.lineEdit_3_14.setStyleSheet("")
        self.lineEdit_3_14.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_3_14.setObjectName("lineEdit_3_14")
        self.lineEdit_3_5 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_3_5.setGeometry(QtCore.QRect(290, 230, 111, 25))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(11)
        self.lineEdit_3_5.setFont(font)
        self.lineEdit_3_5.setStyleSheet("")
        self.lineEdit_3_5.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_3_5.setObjectName("lineEdit_3_5")
        self.lineEdit_3_11 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_3_11.setGeometry(QtCore.QRect(790, 230, 111, 25))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(11)
        self.lineEdit_3_11.setFont(font)
        self.lineEdit_3_11.setStyleSheet("")
        self.lineEdit_3_11.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_3_11.setObjectName("lineEdit_3_11")
        self.label_1_47 = QtWidgets.QLabel(self.tab_3)
        self.label_1_47.setGeometry(QtCore.QRect(210, 420, 71, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_1_47.setFont(font)
        self.label_1_47.setObjectName("label_1_47")
        self.label_fig_3_3 = QtWidgets.QLabel(self.tab_3)
        self.label_fig_3_3.setGeometry(QtCore.QRect(80, 360, 111, 101))
        self.label_fig_3_3.setText("")
        self.label_fig_3_3.setObjectName("label_fig_3_3")
        self.label_1_48 = QtWidgets.QLabel(self.tab_3)
        self.label_1_48.setGeometry(QtCore.QRect(210, 370, 71, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_1_48.setFont(font)
        self.label_1_48.setObjectName("label_1_48")
        self.lineEdit_3_4 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_3_4.setGeometry(QtCore.QRect(290, 135, 111, 25))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(11)
        self.lineEdit_3_4.setFont(font)
        self.lineEdit_3_4.setStyleSheet("")
        self.lineEdit_3_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_3_4.setObjectName("lineEdit_3_4")
        self.line_30 = QtWidgets.QFrame(self.tab_3)
        self.line_30.setGeometry(QtCore.QRect(957, 0, 1, 490))
        self.line_30.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(0, 0, 0);\n"
"border-color: rgb(0, 0, 0);")
        self.line_30.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_30.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_30.setObjectName("line_30")
        self.line_31 = QtWidgets.QFrame(self.tab_3)
        self.line_31.setGeometry(QtCore.QRect(0, 0, 960, 1))
        self.line_31.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.line_31.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_31.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_31.setObjectName("line_31")
        self.line_32 = QtWidgets.QFrame(self.tab_3)
        self.line_32.setGeometry(QtCore.QRect(0, 0, 1, 45))
        self.line_32.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(0, 0, 0);\n"
"border-color: rgb(0, 0, 0);")
        self.line_32.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_32.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_32.setObjectName("line_32")
        self.label_1_49 = QtWidgets.QLabel(self.tab_3)
        self.label_1_49.setGeometry(QtCore.QRect(710, 275, 71, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_1_49.setFont(font)
        self.label_1_49.setObjectName("label_1_49")
        self.lineEdit_3_6 = QtWidgets.QLineEdit(self.tab_3)
        self.lineEdit_3_6.setGeometry(QtCore.QRect(290, 280, 111, 25))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(11)
        self.lineEdit_3_6.setFont(font)
        self.lineEdit_3_6.setStyleSheet("")
        self.lineEdit_3_6.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_3_6.setObjectName("lineEdit_3_6")
        self.label_1_50 = QtWidgets.QLabel(self.tab_3)
        self.label_1_50.setGeometry(QtCore.QRect(210, 130, 71, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_1_50.setFont(font)
        self.label_1_50.setObjectName("label_1_50")
        self.label_1_51 = QtWidgets.QLabel(self.tab_3)
        self.label_1_51.setGeometry(QtCore.QRect(210, 225, 71, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_1_51.setFont(font)
        self.label_1_51.setObjectName("label_1_51")
        self.label_fig_3_4 = QtWidgets.QLabel(self.tab_3)
        self.label_fig_3_4.setGeometry(QtCore.QRect(580, 70, 111, 101))
        self.label_fig_3_4.setText("")
        self.label_fig_3_4.setObjectName("label_fig_3_4")
        self.label_1_52 = QtWidgets.QLabel(self.tab_3)
        self.label_1_52.setGeometry(QtCore.QRect(530, 170, 20, 181))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_1_52.setFont(font)
        self.label_1_52.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_1_52.setAlignment(QtCore.Qt.AlignCenter)
        self.label_1_52.setWordWrap(True)
        self.label_1_52.setIndent(-1)
        self.label_1_52.setObjectName("label_1_52")
        self.label_1_53 = QtWidgets.QLabel(self.tab_3)
        self.label_1_53.setGeometry(QtCore.QRect(710, 225, 71, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_1_53.setFont(font)
        self.label_1_53.setObjectName("label_1_53")
        self.label_1_54 = QtWidgets.QLabel(self.tab_3)
        self.label_1_54.setGeometry(QtCore.QRect(710, 420, 71, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_1_54.setFont(font)
        self.label_1_54.setObjectName("label_1_54")
        self.widget_1_3 = QtWidgets.QWidget(self.tab_3)
        self.widget_1_3.setGeometry(QtCore.QRect(0, 0, 960, 45))
        self.widget_1_3.setStyleSheet("QWidget{\n"
"    border:none;\n"
"    background-color: rgb(255,255,255);\n"
"}\n"
"\n"
"    ")
        self.widget_1_3.setObjectName("widget_1_3")
        self.label_1_55 = QtWidgets.QLabel(self.widget_1_3)
        self.label_1_55.setGeometry(QtCore.QRect(320, 6, 81, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_1_55.setFont(font)
        self.label_1_55.setObjectName("label_1_55")
        self.label_1_56 = QtWidgets.QLabel(self.widget_1_3)
        self.label_1_56.setGeometry(QtCore.QRect(660, 6, 101, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_1_56.setFont(font)
        self.label_1_56.setObjectName("label_1_56")
        self.comboBox_3_1 = QtWidgets.QComboBox(self.widget_1_3)
        self.comboBox_3_1.setGeometry(QtCore.QRect(740, 10, 111, 25))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.comboBox_3_1.setFont(font)
        self.comboBox_3_1.setStyleSheet("QComboBox {\n"
"    \n"
"    \n"
"    border-radius:2;\n"
"    border: 1px solid black;\n"
"    padding:0 0 0 15;\n"
"    margin: 0 0 0 5;\n"
"}\n"
"QComboBox::drop-down {\n"
"    \n"
"    border-top-left-radius: 0;     /* 左上角 */\n"
"    border-top-right-radius: 2;    /* 右上角 */\n"
"    border-bottom-left-radius: 0;  /* 左下角 */\n"
"    border-bottom-right-radius: 2; /* 右下角 */\n"
"    border-left-width :  1px ;\n"
"     border-left-color : darkgray;\n"
"     border-left-style :  solid ;  \n"
"    width: 20px;\n"
"    margin: 0;\n"
"}\n"
"QComboBox::down-arrow{\n"
"    image: url(:/background/down_arrow.svg);\n"
"    width: 13px;\n"
"    height:15px;\n"
"}\n"
"\n"
"\n"
"QComboBox QAbstractItemView::item {\n"
"     height :  25px ;\n"
"     padding-left: 10px;\n"
"}\n"
" \n"
"QListView::item {\n"
"     background :  white ;\n"
"}\n"
" \n"
"QListView::item:hover {\n"
"     background :  #BDD7FD ;\n"
"}")
        self.comboBox_3_1.setEditable(True)
        self.comboBox_3_1.setObjectName("comboBox_3_1")
        self.queding_3_1 = QtWidgets.QPushButton(self.widget_1_3)
        self.queding_3_1.setGeometry(QtCore.QRect(895, 10, 50, 25))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.queding_3_1.setFont(font)
        self.queding_3_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.queding_3_1.setStyleSheet("QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(68, 114, 196);\n"
"    border-radius:0;\n"
"    border: 1px solid rgb(64,64,64);\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(255,255,255);\n"
"    background-color: rgb(0, 0, 127);\n"
"    border-radius:0;\n"
"    border: 1px solid rgb(63,117,191);\n"
"}\n"
"QPushButton:pressed{\n"
"border:2px solid white;\n"
"color:white;\n"
"background-color:rgb(0, 0, 127);border-style:outset;\n"
"font: 8pt;}\n"
"")
        self.queding_3_1.setObjectName("queding_3_1")
        self.label_1_57 = QtWidgets.QLabel(self.widget_1_3)
        self.label_1_57.setGeometry(QtCore.QRect(35, 6, 81, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_1_57.setFont(font)
        self.label_1_57.setObjectName("label_1_57")
        self.lineEdit_3_1 = QtWidgets.QLineEdit(self.widget_1_3)
        self.lineEdit_3_1.setGeometry(QtCore.QRect(120, 10, 113, 25))
        self.lineEdit_3_1.setStyleSheet("border-style: outset; \n"
"      border-width: 0.5px; \n"
"      border-color: black;")
        self.lineEdit_3_1.setObjectName("lineEdit_3_1")
        self.lineEdit_3_2 = QtWidgets.QLineEdit(self.widget_1_3)
        self.lineEdit_3_2.setGeometry(QtCore.QRect(400, 10, 181, 25))
        self.lineEdit_3_2.setStyleSheet("border-style: outset; \n"
"      border-width: 0.5px; \n"
"      border-color: black;")
        self.lineEdit_3_2.setObjectName("lineEdit_3_2")
        self.line_33 = QtWidgets.QFrame(self.tab_3)
        self.line_33.setGeometry(QtCore.QRect(0, 0, 960, 1))
        self.line_33.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.line_33.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_33.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_33.setObjectName("line_33")
        self.line_34 = QtWidgets.QFrame(self.tab_3)
        self.line_34.setGeometry(QtCore.QRect(957, 0, 1, 45))
        self.line_34.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(0, 0, 0);\n"
"border-color: rgb(0, 0, 0);")
        self.line_34.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_34.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_34.setObjectName("line_34")
        self.line_35 = QtWidgets.QFrame(self.tab_3)
        self.line_35.setGeometry(QtCore.QRect(0, 0, 1, 45))
        self.line_35.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(0, 0, 0);\n"
"border-color: rgb(0, 0, 0);")
        self.line_35.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_35.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_35.setObjectName("line_35")
        self.label_5 = QtWidgets.QLabel(self.tab_3)
        self.label_5.setGeometry(QtCore.QRect(770, 470, 181, 20))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(8)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.tabWidget_1.addTab(self.tab_3, "")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(5, 8, 21, 21))
        self.label_2.setStyleSheet("image: url(:/background/lol.png);\n"
"background-color: rgb(38, 80, 157);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(880, 7, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(500, 6, 351, 23))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(10)
        self.progressBar.setFont(font)
        self.progressBar.setStyleSheet("color: rgb(255, 255, 255);")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget_1.setCurrentIndex(0)
        self.comboBox_1_1.setCurrentIndex(-1)
        self.comboBox_2_1.setCurrentIndex(-1)
        self.comboBox_3_1.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "主页"))
        self.label.setText(_translate("MainWindow", "      歪比歪比战队英雄推荐系统"))
        self.label_1_2.setText(_translate("MainWindow", "当前时间："))
        self.label_1_1.setText(_translate("MainWindow", "敌方英雄："))
        self.queding_1_1.setText(_translate("MainWindow", "确定"))
        self.label_1_3.setText(_translate("MainWindow", "当前版本："))
        self.label_1_4.setText(_translate("MainWindow", "推荐对位英雄"))
        self.label_1_6.setText(_translate("MainWindow", "英雄名称："))
        self.label_1_8.setText(_translate("MainWindow", "对位胜率："))
        self.label_1_9.setText(_translate("MainWindow", "对位胜率："))
        self.label_1_10.setText(_translate("MainWindow", "英雄名称："))
        self.label_1_11.setText(_translate("MainWindow", "对位胜率："))
        self.label_1_12.setText(_translate("MainWindow", "英雄名称："))
        self.label_1_13.setText(_translate("MainWindow", "对位胜率："))
        self.label_1_14.setText(_translate("MainWindow", "对位胜率："))
        self.label_1_15.setText(_translate("MainWindow", "英雄名称："))
        self.label_1_16.setText(_translate("MainWindow", "对位胜率："))
        self.label_1_5.setText(_translate("MainWindow", "英雄池内推荐英雄"))
        self.label_1_17.setText(_translate("MainWindow", "英雄名称："))
        self.label_1_7.setText(_translate("MainWindow", "英雄名称："))
        self.label_3.setText(_translate("MainWindow", "@ 歪比歪比战队版权所有2020-2022"))
        self.tabWidget_1.setTabText(self.tabWidget_1.indexOf(self.tab_1), _translate("MainWindow", "打野"))
        self.label_1_18.setText(_translate("MainWindow", "对位胜率："))
        self.label_1_19.setText(_translate("MainWindow", "英雄池内推荐英雄"))
        self.label_1_20.setText(_translate("MainWindow", "英雄名称："))
        self.label_1_21.setText(_translate("MainWindow", "对位胜率："))
        self.label_1_22.setText(_translate("MainWindow", "推荐对位英雄"))
        self.label_1_23.setText(_translate("MainWindow", "对位胜率："))
        self.label_1_24.setText(_translate("MainWindow", "对位胜率："))
        self.label_1_25.setText(_translate("MainWindow", "英雄名称："))
        self.label_1_26.setText(_translate("MainWindow", "英雄名称："))
        self.label_1_27.setText(_translate("MainWindow", "对位胜率："))
        self.label_1_28.setText(_translate("MainWindow", "英雄名称："))
        self.label_1_29.setText(_translate("MainWindow", "对位胜率："))
        self.label_1_30.setText(_translate("MainWindow", "英雄名称："))
        self.label_1_31.setText(_translate("MainWindow", "英雄名称："))
        self.label_1_32.setText(_translate("MainWindow", "当前时间："))
        self.label_1_33.setText(_translate("MainWindow", "敌方英雄："))
        self.queding_2_1.setText(_translate("MainWindow", "确定"))
        self.label_1_34.setText(_translate("MainWindow", "当前版本："))
        self.label_4.setText(_translate("MainWindow", "@ 歪比歪比战队版权所有2020-2022"))
        self.tabWidget_1.setTabText(self.tabWidget_1.indexOf(self.tab_2), _translate("MainWindow", "中单"))
        self.label_1_41.setText(_translate("MainWindow", "推荐对位英雄"))
        self.label_1_42.setText(_translate("MainWindow", "对位胜率："))
        self.label_1_43.setText(_translate("MainWindow", "英雄名称："))
        self.label_1_44.setText(_translate("MainWindow", "英雄名称："))
        self.label_1_45.setText(_translate("MainWindow", "英雄名称："))
        self.label_1_46.setText(_translate("MainWindow", "对位胜率："))
        self.label_1_47.setText(_translate("MainWindow", "对位胜率："))
        self.label_1_48.setText(_translate("MainWindow", "英雄名称："))
        self.label_1_49.setText(_translate("MainWindow", "对位胜率："))
        self.label_1_50.setText(_translate("MainWindow", "对位胜率："))
        self.label_1_51.setText(_translate("MainWindow", "英雄名称："))
        self.label_1_52.setText(_translate("MainWindow", "英雄池内推荐英雄"))
        self.label_1_53.setText(_translate("MainWindow", "英雄名称："))
        self.label_1_54.setText(_translate("MainWindow", "对位胜率："))
        self.label_1_55.setText(_translate("MainWindow", "当前时间："))
        self.label_1_56.setText(_translate("MainWindow", "敌方英雄："))
        self.queding_3_1.setText(_translate("MainWindow", "确定"))
        self.label_1_57.setText(_translate("MainWindow", "当前版本："))
        self.label_5.setText(_translate("MainWindow", "@ 歪比歪比战队版权所有2020-2022"))
        self.tabWidget_1.setTabText(self.tabWidget_1.indexOf(self.tab_3), _translate("MainWindow", "上单"))
        self.pushButton.setText(_translate("MainWindow", "更新数据"))
import background.loginimage_rc
